version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/auth
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # interface web

volumes:
  pgdata:
